version: "3.9"

services:
  api:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./:/app/
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6378:6379'
    volumes:
      - ./data:/data